source/mir/ndslice/topology.d

Also, have you considered using **contiguous** instead of **continuous**? It might be more correct to use contiguous for this occasion.

Fixed typo.

---

source/mir/ndslice/algorithm.d
source/mir/ndslice/allocation.d
source/mir/ndslice/package.d
source/mir/ndslice/slice.d
source/mir/ndslice/stack.d

fixes https://github.com/libmir/mir/issues/213

add stack (concatenation)

---

source/mir/ndslice/package.d

If I understand it correctly, this should fix the following ddoc issue:
http://docs.algorithm.dlang.io/latest/mir_ndslice.html

Escape ndslice for ddoc

---

source/mir/ndslice/algorithm.d

Makes tweaks to the algorithm.d equal documentation to provide additional examples and See Also to Slice.opEqual.

Update algorithm.d equal documentation

---

source/mir/ndslice/slice.d

https://github.com/ldc-developers/ldc/issues/2121

workaround for LDC issue issue 2121

---

doc/Makefile
source/mir/ndslice/chunks.d
source/mir/ndslice/package.d
source/mir/ndslice/slice.d
source/mir/ndslice/topology.d

@andralex @wilzbach  @ljubobratovicrelja @thewilsonator @dataPulverizer 
Mir Algorithm basic API is stable enough and we can start to do reviews! Please help with that)
This PR contains fast multidimensional random access `chunks`. It has multidimensional slicing, builtin dimension transposition, allows to get underlying slice during life time.
Motivation of this addition is cache oriented algorithms. For example, see Chapter 1 at  [The Science of Programming Matrix Computations](http://www.cs.utexas.edu/users/rvdg/tmp/TSoPMC.pdf)

Add ndslice.chunks module

---

source/mir/ndslice/topology.d

Fixing a bug in the way zip checks for lengths and strides.
The way it previously worked did not account for the fact that the foreach loop starts with `i=0`, but only goes through the length of `Slices[1 .. $].length`, so it will unnecessarily check `i=0` and miss the last data point. The fix bumps up `i` to `i+1`
See issue [59](https://github.com/libmir/mir-algorithm/issues/59)

Adjusting zip index

---

source/mir/ndslice/package.d

The chunks module was not listed on the ndslice documentation page.

Add chunks to package.d documentation

---

source/mir/ndslice/topology.d

The way the strides error message work is that two slices could have the same strides when packed and it could trigger. Just making the error message more clear that the slices need to have the same strides when unpacked.

Improving zip strides error message

---

source/mir/ndslice/algorithm.d
source/mir/ndslice/slice.d
source/mir/ndslice/topology.d

This pull request addresses issue #66 that I created.
The `isSlice` function currently performs double-duty, also returning packs information. This change adds in an alias `packsOf` for isSlice. Other adjustments change the behavior where isSlice is currently used.
Update of previous PR #68 (had deleted to clean up my fork, b/c I am git idiot).

Add in packsOf alias for isSlice

---

doc/Makefile

After adding the traits module to ndslice, it was not showing up properly in the docs. I believe adding traits to the doc Makefile will resolve the issue.

Add traits to doc/Makefile

---

doc/Makefile
index.d
source/mir/math/package.d

There is currently no package.d file for mir.math. This pull request adds this file and relevant documentation and functionality (public imports of the relevant submodules of mir.math).
Where a user previously had to write
`import mir.math.sum : sum`
a user now should be able to write
`import mir.math : sum`

Add math/package.d

---

.gitignore

The .gitignore file as currently set up does not take into account Windows development. Testing on Windows generates exe's that must be removed before commiting.

Add exes to .gitignore

---

source/mir/ndslice/dynamic.d
source/mir/ndslice/internal.d

This PR allow user to do not convert slice kind manually when using `mir.ndslice.dynamic`

relax dynamic constraints

---

source/mir/utility.d

See comment at
https://github.com/libmir/mir-random/pull/39#issuecomment-340291639

Remove non-working extMul_X86_64 (used by non-LDC)

---

.travis.yml
source/mir/interpolate/package.d
source/mir/ndslice/algorithm.d
source/mir/ndslice/topology.d

The problem seems to be that in the non-vector fallback path of mir.interpolate.vectorize, input was being overwritten by output. Also x64 wasn't being detected. Please review the "R == 1" case where I made a change that I believe is correct but might be wrong.
~~This pull request doesn't fix the "escaping reference to local variable slice" errors in mir.ndslice.topology.d when compiling with ldc-1.2.0.~~
**EDIT:** Also added workaround for error in "tensor mutation on-the-fly" unittest with DMD x86-64 on non-Windows platforms. Also added workaround to allow compilation with ldc-1.2.0.

Fix unittest/compilation failures

---

source/mir/ndslice/iterator.d

https://github.com/libmir/mir-algorithm/issues/111

Fix issue #111 - nested map calls

---

source/mir/array/primitives.d
source/mir/functional.d
source/mir/internal/memory.d
source/mir/interpolate/constant.d
source/mir/interpolate/linear.d
source/mir/interpolate/spline.d
source/mir/math/common.d
source/mir/math/numeric.d
source/mir/ndslice/concatenation.d
source/mir/ndslice/connect/cpython.d
source/mir/ndslice/dynamic.d
source/mir/ndslice/field.d
source/mir/ndslice/slice.d
source/mir/ndslice/topology.d
source/mir/utility.d

All changes were documentation or variable names except for `MapField.elemenstCount`.
Corrected the spelling there but left a deprecated alias in case anyone was using the
old version. (Unfortunately the compiler doesn't emit a warning when using a deprecated
alias.)

Spelling fixes

---

doc/Makefile
doc/custom.ddoc
doc/run_examples_custom.js

Make all examples at the docs runnable like on dlang.org
Now that I overhauled [run.dlang.io](https://run.dlang.io) this is got pretty easy.
Note:
- that I copied the `run_example.js` over from the dlang.org repo to make updates in the future easier.
- the assert->writeln pipeline isn't run here (it's a PITA to do with Make)
Preview: http://files.wilzbach.me/dlang/mir-algorithm/mir_ndslice_algorithm.html
See also: upcoming Mir series here https://tour.dlang.org/tour/en/dub/mir (anyone can help to fill the blanks - the backend is there)

Make all examples at the docs runnable like on dlang.org

---

doc/Makefile
doc/custom.ddoc
doc/run_examples_custom.js

When people click on open on run.dlang.io, currently a hard-coded version will be inserted.
This PR will remove the need for hard-coding this. However, at run.dlang.io, we only fetch the latest released version (the backend will automagically patch the `dub.sdl`), so when people request `~>0.8.0-alpha.4`, they would get `0.7.0`.
I might change it later, so that both the latest released and latest pre-release version are cached.

Runnable examples: automatically inject the latest version

---

doc/Makefile
doc/custom.ddoc

For now, run.dlang.io only contains the latest stable release.
This will make sure, that this is selected.
I might build the latest unstable release too over the next days, but not today anymore.

Use latest stable version for run.dlang.io for now

---

appveyor.yml

LDC1.7.0 is failing in appveyor https://ci.appveyor.com/project/9il/mir-algorithm/build/1.0.158/job/52dr22f7xajo9dtd
The problem is change of LDC binary url
- old https://github.com/ldc-developers/ldc/releases/download/v1.6.0/ldc2-1.6.0-win64-msvc.zip
- new https://github.com/ldc-developers/ldc/releases/download/v1.7.0/ldc2-1.7.0-windows-x64.7z

Update appveyor.yml for the LDC1.7.0 URL change

---

source/mir/ndslice/algorithm.d

enum doesn't work here because it's a run-time variable, but should be able to make it immutable. dmd crashes when I run dub test, but I think it's unrelated.

eachLower/Upper: make k immutable

---

.gitignore
.travis.yml
source/mir/math/sum.d
source/mir/ndslice/concatenation.d
source/mir/ndslice/connect/cpython.d
source/mir/ndslice/fuse.d
source/mir/ndslice/topology.d
test_examples.sh

A start at fixing https://github.com/libmir/mir-algorithm/issues/141
The script from Phobos only extracts public top-level unittests (so tests inside a struct are not tested for now).
Also the mapping back from the error message is a bit annoying because it doesn't add empty whitespace, so the line numbers are off.
Anyhow, it's a start.

Start fixing public test imports

---

source/mir/ndslice/topology.d

Issue: #179 
SliceKind Selectors will copy over labels while returning a new slice.
Modified: Universal, Canonical, assumeCanonical, assumeContiguous
Commands ran:
(Cleared trailing white spaces in VS Code )

topology.d: Added label support for SliceKind selectors

---

source/mir/ndslice/slice.d

Added labels support for lightScope, lightImmutable, lightConst, toConst
Commands ran:
I couldn't find any unittests to add to. Should I write any?

slice.d: Added label support for Slice selectors

---

source/mir/math/stat.d

`CentralTendency` and `average` can easily be expanded in the future to accommodate new functions. 
One potential downside is that other functions that may be passed to average may require something other than `Summation`. I can't think of it now, but it's possible. 
I'm also not sure if `centerImpl` is the best approach, but it works.

Add center (and average)

---

source/mir/math/stat.d
source/mir/ndslice/sorting.d

Implementation of `median`, which just uses `topN` primarily for the implementation. 
I also added some of the other `medianOf` functions from phobos, which helped handling small slices. 
I can work on additional improvements for `topN` separately when I get some guidance on these comments:
https://github.com/libmir/mir-algorithm/pull/250#issuecomment-623584804
https://github.com/libmir/mir-algorithm/pull/250#issuecomment-623609532

Add median

---

source/mir/interpolate/polynomial.d
source/mir/math/numeric.d

This is an attempt to make `prod` implemented more like `sum` so that it can handle multiple algorithms. In particular, it can theoretically handle the original algorithm and a `naive` algorithm. 
I labeled this WIP because I am getting some kind of out of memory errors (I'm getting a dmd error message about an error flag that is minus a large number), even with dflags' -lowmem. I am away from my desktop computer and using my laptop with only 8GB RAM. I wanted to check if I get the same thing with the CI.

Make prod more like sum

---

source/mir/math/stat.d

Adding unittests in `center` for `gmean` and `median`. Also fixing some formatting of unittests in `mir.math.stat` to be more consistent.

Add center UTs/adj stat UT

---

source/mir/math/numeric.d
source/mir/math/stat.d
source/mir/math/sum.d

This PR adds the overloads for `sum` that exist for `prod` and some of the other statistical functions already.

Add overloads for sum

---

source/mir/math/numeric.d
source/mir/math/stat.d
source/mir/math/sum.d
source/mir/ndslice/topology.d

This PR fixes the issue with `mir.stat` & `mir.numeric` to force the relevant functions to return floating point or complex types.
It also adds a variadic overload to `hmean` for consistency with the other functions and makes a few other quality of life improvements.

Fix stat/numeric FP issue / Add variadic hmean overload

---

source/mir/math/stat.d

This PR adds a `variance` function to `mir.stat`. 
I wanted to do one moment function before moving on to `skewess`, `kurtosis`, and the others to make sure the general structure is correct.

Add variance

---

source/mir/ndslice/slice.d

Facilitates easier access to slice contents, especially when not contiguous.

Add at/numStride/indexStride

---

source/mir/math/stat.d

This function is a generic way to calculate different measures of statistical dispersion, including but not limited to variance (as mean squared deviation), mean absolute deviation, median squared deviation, and median absolute deviation. This function could theoretically handle more general measures of statistical dispersion, such as interquartile range, though this is not tested yet.
I re-used a `square` function from earlier. I tried to replace it without success.
EDIT: Typo

Add dispersion function

---

source/mir/math/stat.d
source/mir/ndslice/sorting.d

The fix to [issue 283](https://github.com/libmir/mir-algorithm/issues/283) [here](https://github.com/libmir/mir-algorithm/commit/b78e39d56e77a5b1a4570e9cf5bb8da11a86b818) marks `partitionAt` as `nothrow` without also marking some of the other recursive functions. This means that when replacing `version(mir_test_topN)` with `version(mir_test)` then a bunch of UTs will fail. The underlying issue is that there is a bug in the compiler front-end that prevents attribute inference in recursive functions like this. I discuss the DMD bug in a comment [here](https://github.com/libmir/mir-algorithm/pull/276#issuecomment-647147722). The simplest solution is to also mark `partitionAtPartitionMedian` and `partitionAtPartition` as `pure nothrow`, which is what this PR does (and marks other …

Update UT version/purity

---

dub.sdl
source/mir/math/stat.d

This algorithm can be useful when trying to calculate to calculate the `variance` of an already `center`ed slice. Alternately, it can be useful in the context of linear regression where the residuals are assumed to have zero mean. More generally, it can be thought of as just the mean of the squares of the input. It can also be used to obtain the sum of the squares.

Add assumeZeroMean VarianceAlgo

---

source/mir/ndslice/topology.d

I always forget the proper way to arbitrarily combine `zip` and `map` in more complex examples.

Add map zipped tensor UT

---

source/mir/math/stat.d

This improves documentation for `median`.
It also makes a few changes, including to the output type. I changed it to `meanType` because when the length is even then a `mean` must be calculated and I think it is better to have the right value than potentially provide a wrong `int` value. It provides more information to why one cannot pass a const or immutable slice when `allowModify=true`. However, this does not resolve issue [293](https://github.com/libmir/mir-algorithm/issues/293), which is for the case when `allowModify=false`.

Improve docs for median

---

source/mir/math/stat.d

Needed for `mir-stat` to get `dispersion` UT to pass.

Make statistical types public

---

source/mir/math/stat.d

One motivation for including these was to re-use operations across higher-level moments. With higher-level moments in `mir.stat`, it prompted me to re-think this approach. One issue with these mixins is that they do not show up properly in documentation. The downside is code duplication.

Remove moment_ops/outputRange_ops mixins

---

source/mir/math/stat.d

Adds versions for handling dynamic arrays and those for which hasAsSlice is true.

Update median implementation

---

source/mir/math/stat.d

I've been having some difficulty with `mir.stat.descriptive.quantile` getting `asSlice` to consistently work and figured I should add tests to `mir.math.stat` to ensure the functionality works properly there.

Increase stat code cov

---

source/mir/math/sum.d

I did this more too satisfy my own curiosity in terms of potentially adding the same functionality to `mir-stat` at some point in the future.
One of the things I noticed is that `MeanAccumulator` does not have `+` and `-` defined in the same way that `Summator` does. It doesn't really have a big impact in this case because I avoid modifying `count`. However, it means the logic for adjusting it is in `MovingAverage` instead of `MeanAccumulator`. I would guess, without testing myself and not being 100% sure, that when compiling with `-O` the adding and subtraction of count is elided.

Adjust MovingAverage UT to use MeanAccumulator and be @nogc

---

include/mir/series.h

The iterator for the C++ `mir_series<>` type template is no longer compatible with `std::iterator_traits` because of [recent changes](https://en.cppreference.com/w/cpp/iterator/iterator_traits) in the standard. Since `value_type` and other members aren't defined, `iterator_traits` has no members, and code that attempts use the iterator traits fails to compile.

add required types for C++ iterator traits

---

source/mir/ndslice/internal.d

```
When the switch is provided, '[auto] ref in' becomes illegal in the parser.
This little trick, using static if + mixin, allow to have a different function
based on whether the switch is used or not.
```
If I could  get a point release, that would allow me to make progress with https://github.com/dlang/dmd/pull/11632

Adapt code to support -preview=in

---

dub.sdl
source/mir/algorithm/iteration.d
source/mir/bignum/fp.d
source/mir/math/stat.d
source/mir/math/sum.d

This PR addresses the built-in complex deprecation. It currently does not pass CI because `mir.math.sum`. The offending line is below. In particular, `hasElaborateAssign!T` is true for `Complex!U` instead of false for the built-in types. 
```d
static if (is(T == class) || is(T == interface) || hasElaborateAssign!T)
static assert (summation == Summation.naive,
"Classes, interfaces, and structures with "
~ "elaborate constructor support only naive summation.");
```
Not sure how you want to handle (either special case it or just rely on other summation techniques for `Complex`).

Address built-in complex deprecation

---

source/mir/bignum/fixed.d
source/mir/bignum/integer.d
source/mir/bignum/low_level_view.d

Adds in support for hex literals with underscores for better readability. Should not change the existing behavior, but added several unit-tests to verify that the underscore literals are equivalent to non-underscore literals.
Note: in `static BigUIntView fromHexString()`, we actually over-allocate for the amount of coefficients that we need
https://github.com/libmir/mir-algorithm/blob/085212a0df9962d13ac626778405bd71c1e2ade9/source/mir/bignum/low_level_view.d#L572
This is sliced down to the amount that was actually taken here (where j represents the number of non-underscore characters)
https://github.com/libmir/mir-algorithm/blob/085212a0df9962d13ac626778405bd71c1e2ade9/source/mir/bignum/low_level_view.d#L680
This does increase the initial memory footprint (especially as the input string …

Add in support for hex literals using underscores

---

.github/workflows/ci.yml
test_travis.sh

Adds in GitHub Actions support to replace the now-disabled Travis-CI flow. 
Does not include aarch64 support -- that is coming soon, as we can run the tests natively on CircleCI.

Add GitHub Actions to replace Travis-CI

---

source/mir/format.d

The important changes are the qualifications of the parameters to the `text` and `print` overloads which in essence strips off either `const` or `immutable` qualifier from the type(s) `A`. In calls such as
```d
text(int.init)
text(const(int).init)
text(immutable(int).init)
...
```
all result in the same template instance of `text` potentially saving time and space requirements on compilation and binary sizes.

Use const parameters in mir.format to reduce template bloat

---

source/mir/format.d

Reverts libmir/mir-algorithm#359

Revert "Use const parameters in mir.format to reduce template bloat"

---

source/mir/base64.d

This PR adds in a relatively simplistic Base64 (de|en)coder (#369)
It is incredibly simple by design, as well as being `@nogc @safe pure` (except for the functions that do not take in Appenders). I've only tested it with some small bits of data, but, it should easily scale up to handle an infinite amount of data.
I have not verified how this fares with systems that are big-endian -- would love more insight on that regard.
Let me know if this needs any more work. Thanks!

Add simple base64 de/encoding

---

source/mir/bignum/decimal.d
source/mir/bignum/low_level_view.d

This PR adds support for decimal literals specified in #365. Examples of these literals are:
```
2000000000.e0 
4000000000.e0 
5000000000.e0 
-2000000000.e0 
-4000000000.e0 
-5000000000.e0
```
This is a relatively trivial fix, and shouldn't significantly impact the existing parsing code. Let me know if this needs any further work.

Add fixes to both the Decimal and DecimalView impls to allow exponents to follow dots

---

source/mir/string_map.d

You very seldom need to qualify a templated (member) function as `@system`. What you should do is qualify unittests as @safe and then qualify the parts of the (templated) library code as @trusted in only the statements that require it. Or avoid pointer arithmetic and such as done in this PR.

Make String.opBinaryRight @safe when possible and qualify test as @safe

---

.github/workflows/ci.yml
.github/workflows/compilers.json
README.md
dub.sdl
meson.build
source/mir/ndslice/allocation.d
source/mir/ndslice/chunks.d
source/mir/ndslice/concatenation.d
source/mir/ndslice/connect/cpython.d
source/mir/ndslice/dynamic.d
source/mir/ndslice/field.d
source/mir/ndslice/filling.d
source/mir/ndslice/fuse.d
source/mir/ndslice/internal.d
source/mir/ndslice/iterator.d
source/mir/ndslice/mutation.d
source/mir/ndslice/package.d
source/mir/ndslice/slice.d
source/mir/ndslice/sorting.d
source/mir/ndslice/topology.d
source/mir/ndslice/traits.d

See https://github.com/libmir/mir-ion/issues/16 for more detail.

Update CI files to include requested changes

---

source/mir/ediff.d
source/mir/math/func/normal.d

As discussed [here](https://github.com/libmir/mir-algorithm/commit/a828eb1da6832fd4d57794141663deb09d58085d#r70070443)

Provide alternate API for normal distribution functions, deprecate existing API

---

source/mir/algebraic_alias/ion.d
source/mir/algebraic_alias/json.d
source/mir/bignum/decimal.d
source/mir/interpolate/constant.d
source/mir/interpolate/generic.d
source/mir/interpolate/linear.d
source/mir/interpolate/polynomial.d
source/mir/interpolate/spline.d
source/mir/math/stat.d
source/mir/ndslice/internal.d
source/mir/ndslice/slice.d
source/mir/rc/package.d
source/mir/series.d

Based on issue #41  left off the documentation imports for the ndslice package.d since the documentation in there already makes it a bit obvious that they are available.

Add documentation comments for public imports

---

source/mir/algorithm/iteration.d
source/mir/appender.d
source/mir/bignum/low_level_view.d
source/mir/container/binaryheap.d
source/mir/interpolate/constant.d
source/mir/interpolate/generic.d
source/mir/interpolate/linear.d
source/mir/interpolate/polynomial.d
source/mir/interpolate/spline.d
source/mir/ndslice/iterator.d
source/mir/ndslice/slice.d
source/mir/rc/array.d
source/mir/rc/context.d
source/mir/rc/ptr.d
source/mir/rc/slim_ptr.d
source/mir/small_array.d
source/mir/small_string.d

---
1. When building mir-algorithm there is a new deprecation warning:
```
mir-algorithm/source/mir/appender.d(219,16): Deprecation: returning `this._buffer.length ? this._buffer[0..this._currentLength] : this._scopeBuffer()[0..this._currentLength]` escapes a reference to parameter `this`
mir-algorithm/source/mir/appender.d(217,16):        perhaps change the `return scope` into `scope return`
```
Fixed by annotating the `ScopedBuffer.data()` property with `return`.
---
2. When building a program using `-dip1000` that uses `mir.ndslice.sorting`, there is a new error:
```
mir-algorithm/source/mir/ndslice/sorting.d(157,30): Error: escaping reference to stack allocated value returned by `sort(sliced(ar))`
```
Fixed by swapping `scope return` for `return scope` in `mir_slice.field()`, which …

Fix DIP1000 related deprecation warnings and errors in v2.100.0-rc.1

---

source/mir/string_map.d

For sake of compliance with `T[string]` when `is(T == const)`.
The primary need is `const(T)` where `is(T == class)`.
Ready for prel review, @9il.

Add support for const values in StringMap

---

source/mir/algorithm/iteration.d

Thought these might be useful.

Add additional filter UT examples

---

source/mir/serde.d

PR on the mir-ion side will follow shortly.
Idea is that you can do this:
```d
@serdeEnumProxy!uint
// equivalent to @serdeProxyCast @serdeEnumProxy!uint
enum Foo
{
a = 1,
b = 2
}
```
and Foo will be
1. serialized by int (as usual with serdeProxy)
2. allows other values than 1 and 2 to be (de)serialized

add `@serdeProxyCast`, `@serdeEnumProxy` UDAs

---

source/mir/algorithm/iteration.d

This adds an additional UT example for the case where you want to filter a slice based on a particular row or column. This idiom is very common in `dplyr`/`pandas`. 
One thing that would make this even easier for the Data Frame case is if there were an easy way to index or select by label. For instance, in the example here [1], `dataframe["balance"]` or `dataframe.select!1("balance")` or something like that would return the column associated with the "balance" label. 
[1] http://mir-algorithm.libmir.org/mir_ndslice_allocation.html#.slice

Add additional filter UT example

---

source/mir/parse.d

This is blocking https://github.com/dlang/dmd/pull/14218
Depending on the specific output of `.stringof` is bad practice, like the spec says:
> Implementation Defined: The string representation for a type or expression can vary.

Don't depend on `stringof` in `mir.parse` test

---

source/mir/date.d

It can be useful to work with dates as year-months, dropping the day.

Add support for YearMonth dates

---

source/mir/bignum/internal/phobos_kernel.d
source/mir/math/numeric.d
source/mir/numeric.d

This is a mixed bag commit:
- phobos_kernel.d: ddoc syntax
- mir/math/numeric.d: just removed DivisionType as its also not documented in
factorial
- mir/numeric.d: just added empty docs for lowerBound, upperBound,
steps. Some of those are not used at all in the function.

Fix `dub build --build=docs` or `dub build --build=ddox`

---

source/mir/date.d

An alternative to PR #436 based on some of the discussion there. 
I remove the add!"X" from `YearMonth` and `YearQuarter` (leaving it for `YearMonthDay` and `Date`). I set up `opBinary` and `opOpAssign` for them as well. I also provide some additional UT examples.
One thing to be aware of is that if you convert a `Date` to a `YearMonth` or `YearQuarter` and then back to a `Date`, there can be some tricky things happening with getting the dates back to how they should be. <s>It's less complicated for my examples because I start them on the first of the month, but if you want everything as of the 10th of the month, then it requires some additional cleanup afterward with this `iota` approach. </s> I added another commit fixing the year example in `Date` so that it is a little bit simpler, …

Add mir.date.d operator overloading, UTs

---

meson.build
source/mir/math/func/hermite.d

I just have the coefficients here and use `mir.polynomial` to produce the results as needed.
I set them up as `enums` so hopefully it is all CTFE-able. 
I plan on making use of the Hermite polynomials for the Cornish-Fisher expansion in `mir-stat`, but I figured it could have use in more places than just there, which is why I added it to `mir-algorithm`, though I am indifferent as to which project or where in the project it would be.

Add hermite polynomial coefficients

---

source/mir/format.d

It'll need a tag (due to holding up phobos PR) please.

Fix #445 remove U+23F4 that was allocated in Unicode 7 from test

---

source/mir/serde.d

Helps cleans up the output of `-vtls` and should not change anything in behavior as well.
See also https://github.com/libmir/mir-core/pull/77

Avoid TLS variables in templates

---

README.md

Adjusting the Github Action button code based on https://github.com/badges/shields/issues/8671
I did the same on mir-stat and it worked (the mir-algorithm version looks a little more complicated but I think the change should still work, open to changes).

Fix github actions button

---

source/mir/math/sum.d

Addresses issue https://github.com/libmir/mir-algorithm/issues/454.
Hopefully checked enough that it works. As is, changes to get working are relatively minimal. Ideally the compiler should be able to optimize away the removal of moves for the const/immutable case.

Make sum work with const slices

---

source/mir/ndslice/package.d

I only changed the code comments to update the median filter example for docs. did not touch anything else.

Update package.d doc for median filter example
