libmir/mir-algorithm

- source/mir/ndslice/selection.d
- source/mir/ndslice/slice.d
Better fix the typo now than latter, e.g. https://en.wikipedia.org/wiki/Continuous_function
> Rename continious -> continuous

- .travis.yml
@9il you probably know best what architectures you plan to support, but I thought having a simple config here doesn't hurt. 
(I already enabled the repo)
> Add simple travis configuration

- source/mir/ndslice/cursor.d
Slowly starting to get used to the new API - so I started very simple with a test. More to follow soon ;-)
> Add tests to IotaCursor

- source/mir/ndslice/iterator.d
- source/mir/ndslice/topology.d
> fix issue #21

- index.d
index.d needs to be updated to include chunks module.
> Update index.d for chunks module

- source/mir/ndslice/algorithm.d
Addressing issue #82.
Note: while testing I get a message "Deprecation: use -g instead of -gc" twice.
> Add includeDiagonal switch to eachUploPair

- source/mir/ndslice/algorithm.d
I noticed a bug in the implementation of eachUploPair. I discussed it on the previous PR here:
https://github.com/libmir/mir-algorithm/pull/83
> Fix eachUploPair while condition

- source/mir/utility.d
Was previously removed: https://github.com/libmir/mir-algorithm/pull/106
Changing the return type of the helper function from a struct to
`ulong[2]` was the key to make the Windows 64 version stop crashing.
Also updated the unit test to verify that the multiplication has
the correct result.
> Restore non-LDC X86_64 assembly code in extMul

- .travis.yml
- appveyor.yml
- circle.yml
- source/mir/functional.d
- source/mir/graph/tarjan.d
- source/mir/graph/utility.d
- source/mir/ndslice/allocation.d
- source/mir/ndslice/iterator.d
- source/mir/ndslice/slice.d
- source/mir/ndslice/sorting.d
- source/mir/ndslice/topology.d
- source/mir/series.d
the implementation does not use recursion.
> add Tarjan algorithm

- cpp_example/main.cpp
- doc/Makefile
- dub.sdl
- include/mir/numeric.h
- meson.build
- source/mir/algorithm/iteration.d
- source/mir/cpp_export/numeric.d
- source/mir/numeric.d
requires the latest mir-core patch https://github.com/libmir/mir-core/commit/4e40630ad8818fbc3c1eb50da21d22598f4f0e73
> extend findRoot

- source/mir/rc/array.d
- source/mir/rc/context.d
- source/mir/rc/ptr.d
- source/mir/type_info.d
> relax @nogc, @safe and pure attrs for types destructors used in RC.

- source/mir/algorithm/iteration.d
- source/mir/appender.d
- source/mir/format.d
- source/mir/math/stat.d
- source/mir/math/sum.d
- source/mir/ndslice/chunks.d
- source/mir/ndslice/dynamic.d
- source/mir/ndslice/filling.d
- source/mir/ndslice/slice.d
- source/mir/ndslice/topology.d
- source/mir/rc/array.d
- source/mir/rc/package.d
- source/mir/series.d
Better reviewed commit-by-commit.
> Clean up upcoming deprecations

- source/mir/appender.d
- source/mir/math/stat.d
- source/mir/math/sum.d
> rework sum, appender, and mean

- source/mir/ndslice/sorting.d
It looks like the last two PRs are failing on CircleCI and it comes to not including some imports in new unittests and then fails. I tried adding these back and hopefully that fixes the issue. 
For some reason, I couldn't see CircleCI when preparing prior PRs.
> Try to fix CircleCI failing

- source/mir/ndslice/sorting.d
Modifying the implementation from phobos in terms of iterators. Results in less dependency on phobos.
> Add pivotPartition

- source/mir/math/stat.d
- source/mir/ndslice/sorting.d
This enhances `partitionAt` so that it uses the same algorithm as phobos.
> Enhance partitionAt

- source/mir/math/numeric.d
- source/mir/math/stat.d
- source/mir/math/sum.d
* Add variadic overloads to sum
* Add sum overloads
* Remove sum variadic template
* Remove prod/mean variadic templates
> Add overloads for sum (#264) (#8)

- source/mir/math/stat.d
Addresses issue [269](https://github.com/libmir/mir-algorithm/issues/269)
> Adjust center UT

- source/mir/math/stat.d
Implements standard deviation by calling `variance` and then `sqrt`.
Also fixes up some documentation.
> Add standard deviation

- source/mir/math/stat.d
The stat docs weren't properly blocking out the parameters for many template arguments.
> Fix stat docs

- source/mir/ndslice/topology.d
Based on suggestion [here](https://github.com/libmir/mir-algorithm/pull/289#issuecomment-650470767).
> Add one more vmap example

- source/mir/ndslice/sorting.d
> Change mir_test_topN to mir_test

- source/mir/math/sum.d
Needed for `mir-stat`. Also makes a few others `package(mir)` that might be useful.
> Make ResolveSummationType package(mir)

- source/mir/math/stat.d
Some minor fixups to `mir.math.stat`.
> Minor mir.math.stat fixups

- source/mir/ndslice/sorting.d
Addresses issue [334](https://github.com/libmir/mir-algorithm/issues/334) with some other fixups.
> Add makeIndex UT, improve docs

- .github/workflows/ci.yml
`dmd-master` is continually broken -- there's no point in testing.
> Add Windows CI flow, remove dmd-master testing

- source/mir/stdio.d
Ready for review and merge, @9il.
> Various improvements to mir.stdio

- source/mir/date.d
> Add YearQuarter

- README.md
Fix link typo discussed here: https://github.com/libmir/mir-algorithm/pull/449
> Fix button link typo
